-- 视频信息表
CREATE TABLE `video_info` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `title` varchar(200) NOT NULL COMMENT '视频标题',
  `description` text COMMENT '视频描述',
  `cover_url` varchar(500) DEFAULT NULL COMMENT '封面图URL',
  `video_url` varchar(500) NOT NULL COMMENT '视频URL',
  `duration` int DEFAULT '0' COMMENT '视频时长(秒)',
  `format` varchar(20) DEFAULT NULL COMMENT '视频格式',
  `file_size` bigint DEFAULT '0' COMMENT '文件大小(字节)',
  `source` tinyint NOT NULL DEFAULT '1' COMMENT '来源 1-上传 2-YouTube 3-其他',
  `source_platform` varchar(50) DEFAULT NULL COMMENT '来源平台',
  `original_url` varchar(500) DEFAULT NULL COMMENT '原始URL',
  `language` varchar(10) NOT NULL DEFAULT 'en' COMMENT '语种代码',
  `level` tinyint NOT NULL DEFAULT '1' COMMENT '难度等级 1-入门 2-初级 3-中级 4-高级',
  `category_id` bigint DEFAULT NULL COMMENT '分类ID',
  `tags` varchar(500) DEFAULT NULL COMMENT '标签(逗号分隔)',
  `play_count` int NOT NULL DEFAULT '0' COMMENT '播放次数',
  `collect_count` int NOT NULL DEFAULT '0' COMMENT '收藏次数',
  `has_subtitle` tinyint NOT NULL DEFAULT '0' COMMENT '是否有字幕 0-否 1-是',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态 0-下架 1-上架',
  `upload_user_id` bigint DEFAULT NULL COMMENT '上传用户ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '是否删除 0-否 1-是',
  PRIMARY KEY (`id`),
  KEY `idx_category_id` (`category_id`),
  KEY `idx_language` (`language`),
  KEY `idx_status` (`status`)
) COMMENT='视频信息表';
